#!/bin/zsh

# To run: ./do-uncrustify

~/uncrustify -c uncrustify.cfg --no-backup G2-edit/*.h
~/uncrustify -c uncrustify.cfg --no-backup G2-edit/*.c
~/uncrustify -c uncrustify.cfg --no-backup G2-edit/*.cpp
~/uncrustify -c uncrustify.cfg --no-backup G2-edit/*.mm
