#!/bin/zsh

# To run: ./do-uncrustify

~/uncrustify -c uncrustify.cfg --no-backup G2\ Gui/*.h
~/uncrustify -c uncrustify.cfg --no-backup G2\ Gui/*.c
~/uncrustify -c uncrustify.cfg --no-backup G2\ Gui/*.cpp
~/uncrustify -c uncrustify.cfg --no-backup G2\ Gui/*.mm
